// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  token: 'c66002a0989a4a2f93ef83c620ae4a8a',
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
